//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Servicios {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class ConfigGeneral : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfigGeneral defaultInstance = ((ConfigGeneral)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfigGeneral())));
        
        public static ConfigGeneral Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\JUAN DIEGO\\Documentos\\RUTAIMAGES\\")]
        public string RutaImagenes {
            get {
                return ((string)(this["RutaImagenes"]));
            }
            set {
                this["RutaImagenes"] = value;
            }
        }
    }
}
